### ISSUE TITLE
Repo should be made private

### ISSUE THREAD

**Issue by Muon** [Trontor/COMP30020---Declarative-Programming#4]
I’m the current head tutor for Declarative Programming. In the interest of academic integrity, I’d like to request that you make private or remove the Declarative Programming-related content you have published on your GitHub account.

It is important to us that students do their own work, and testing their own code is part of the assessment!

Could you please do this today or tomorrow, and notify me when you have done so? Thanks.

**Comment by Trontor** [comment]
gm supposed "current head tutor for Declarative Programming". When I was in my third year of uni (Bachelor of Science), I was fortunate enough to be the Head Tutor for Object Oriented Software Development. 

Throughout my tenure (as I was completing my bachelors simultaneously), I took the time to develop brand new assessment pieces that ensured students were challenged with novel, fun problems that they couldn't easily find online.

I didn't even think to DMCA code.

If you can submit a formal request via your official university email to trontor@mailinator.com, it would be appreciated, so I can verify your claim.

I would also recommend taking a look at Mixtral 8x7B Instruct, as that might be a more prevalent threat to academic integrity.

**Comment by Trontor** [comment]
closed due to [concerns about social engineering](https://tukaani.org/xz-backdoor/) via GitHub
